- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - heat-translator-tox-py37-tp:
            voting: false

- job:
    name: heat-translator-tox-py310-tp
    parent: openstack-tox-py310
    description: |
      Run tests for heat-translator project.

      Uses tox with the ``py310-tp`` environment.
    vars:
      tox_envlist: py310-tp
